{melodic} ros-distro.inc: add mapping for python-six for cob-twist-controller
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python-six' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-twist-controller_0.8.11-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'cob-twist-controller' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-cartesian-controller_0.8.11-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-twist-controller_0.8.11-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-control_0.8.11-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cob-twist-controller'
NOTE: Runtime target 'cob-twist-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-twist-controller']
ERROR: Nothing RPROVIDES 'cob-script-server' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-cartesian-controller_0.8.11-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-twist-controller_0.8.11-1.bb RDEPENDS on or otherwise requires it)
cob-script-server was skipped: Recipe is blacklisted: Requires cob-mimic, cob-sound->vlc which requires meta-multimedia to be included
NOTE: Runtime target 'cob-script-server' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-script-server']
ERROR: Nothing RPROVIDES 'cob-cartesian-controller-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-cartesian-controller_0.8.11-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cob-cartesian-controller-dev'
NOTE: Runtime target 'cob-cartesian-controller-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-cartesian-controller-dev']
ERROR: Nothing RPROVIDES 'cob-cartesian-controller' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-cartesian-controller_0.8.11-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-control_0.8.11-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cob-cartesian-controller'
NOTE: Runtime target 'cob-cartesian-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-cartesian-controller']
ERROR: Nothing RPROVIDES 'packagegroup-ros-world-melodic' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, webos-melodic-thud/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-world.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-world-melodic'
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic']
ERROR: Nothing RPROVIDES 'cob-control' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-control_0.8.11-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cob-control'
NOTE: Runtime target 'cob-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-control']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-six' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-twist-controller_0.8.11-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-six' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-six']
ERROR: Nothing RPROVIDES 'cob-twist-controller-dev' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-twist-controller_0.8.11-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cob-twist-controller-dev'
NOTE: Runtime target 'cob-twist-controller-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-twist-controller-dev']

and

ERROR: Nothing RPROVIDES 'cob-twist-controller' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-control_0.8.11-1.bb RDEPENDS on or otherwise requires it)
cob-twist-controller was skipped: Recipe is blacklisted: Requires cob-script-server->cob-mimic, cob-sound->vlc which requires meta-multimedia to be included
NOTE: Runtime target 'cob-twist-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-twist-controller']
NOTE: Runtime target 'cob-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-control', 'cob-twist-controller']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'cob-control', 'cob-twist-controller']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'cob-control', 'cob-twist-controller']
NOTE: Runtime target 'cob-control-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-control-dev', 'cob-twist-controller']
ERROR: Nothing RPROVIDES 'cob-cartesian-controller' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-control/cob-control_0.8.11-1.bb RDEPENDS on or otherwise requires it)
cob-cartesian-controller was skipped: Recipe is blacklisted: Requires cob-script-server->cob-mimic, cob-sound->vlc which requires meta-multimedia to be included
NOTE: Runtime target 'cob-cartesian-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-cartesian-controller']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>