{melodic} multisense-{lib,ros}: fix various build issues
* remove dependency on unavailable yaml-cpp-native:
ERROR: Nothing PROVIDES 'yaml-cpp-native' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/multisense-ros/multisense-ros_4.0.3-1.bb DEPENDS on or otherwise requires it). Close matches:
  mcpp-native
  yasm-native
  libyaml-native
NOTE: Runtime target 'multisense' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'multisense', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'multisense', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'multisense', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'multisense-cal-check' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-cal-check', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'multisense-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-bringup', 'multisense-ros', 'yaml-cpp-native']
NOTE: Runtime target 'multisense-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-ros', 'yaml-cpp-native']
ERROR: Nothing RPROVIDES 'multisense-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/multisense-ros/multisense_4.0.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'multisense-dev'
NOTE: Runtime target 'multisense-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-dev']

WARNING: multisense-lib-4.0.3-1-r0 do_package: QA Issue: multisense-lib: Files/directories were installed but not shipped in any package:
  /opt/ros/melodic/lib/libMultiSense.so.3.8
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
multisense-lib: 1 installed and not shipped files. [installed-vs-shipped]
WARNING: multisense-lib-4.0.3-1-r0 do_package_qa: QA Issue: package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/DeviceInfoUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/ImageCalUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/LidarCalUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/ImuTestUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/ChangeIpUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/FlashUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/ImuConfigUtility
package multisense-lib contains bad RPATH multisense-lib/4.0.3-1-r0/devel/lib in file multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/multisense_lib/SaveImageUtility [rpaths]
ERROR: multisense-lib-4.0.3-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: multisense-lib path '/work/core2-64-oe-linux/multisense-lib/4.0.3-1-r0/packages-split/multisense-lib/opt/ros/melodic/lib/libMultiSense.so' [dev-so]
ERROR: multisense-lib-4.0.3-1-r0 do_package_qa: QA Issue: /opt/ros/melodic/lib/multisense_lib/SaveImageUtility contained in package multisense-lib requires libMultiSense.so.3.8()(64bit), but no providers found in RDEPENDS_multisense-lib? [file-rdeps]
ERROR: multisense-lib-4.0.3-1-r0 do_package_qa: QA Issue: /opt/ros/melodic/lib/multisense_lib/MultiSenseUpdater contained in package multisense-lib requires /bin/bash, but no providers found in RDEPENDS_multisense-lib? [file-rdeps]
ERROR: multisense-lib-4.0.3-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: multisense-lib-4.0.3-1-r0 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: multisense-lib/4.0.3-1-r0/temp/log.do_package_qa.32028
ERROR: Task (generated-recipes/multisense-ros/multisense-lib_4.0.3-1.bb:do_package_qa) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>