{melodic} adi-driver, rqt-rviz: blacklist based on ogre instead of unknown-victim
* fixes:
ERROR: Nothing PROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/adi-driver/adi-driver_1.0.3.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb DEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: Requires python-qt-binding which requires meta-qt5 to be included and ogre which is not available
ERROR: Nothing PROVIDES 'rviz-imu-plugin' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/adi-driver/adi-driver_1.0.3.bb DEPENDS on or otherwise requires it)
rviz-imu-plugin was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included; ogre: Requires rviz which depends on unavailable ogre
ERROR: Nothing RPROVIDES 'rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/adi-driver/adi-driver_1.0.3.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb RDEPENDS on or otherwise requires it)
rviz was skipped: Recipe is blacklisted: Requires python-qt-binding which requires meta-qt5 to be included and ogre which is not available
NOTE: Runtime target 'rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz']
ERROR: Nothing RPROVIDES 'rviz-imu-plugin' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/adi-driver/adi-driver_1.0.3.bb RDEPENDS on or otherwise requires it)
rviz-imu-plugin was skipped: Recipe is blacklisted: Requires qtbase which requires meta-qt5 to be included; ogre: Requires rviz which depends on unavailable ogre
NOTE: Runtime target 'rviz-imu-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-imu-plugin']
ERROR: Nothing RPROVIDES 'rqt-rviz-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-rviz-dev'
NOTE: Runtime target 'rqt-rviz-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-rviz-dev']
ERROR: Nothing RPROVIDES 'rqt-rviz' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rqt-rviz'
NOTE: Runtime target 'rqt-rviz' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-rviz']
ERROR: Nothing RPROVIDES 'rqt-gui-cpp' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-rviz/rqt-rviz_0.6.0.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mapviz/mapviz_1.2.0-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt-gui-cpp_0.5.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt/rqt_0.5.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rosmon/rqt-rosmon_2.2.1-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/rqt-image-view/rqt-image-view_0.4.14-1.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>