{melodic} ros-reflexxes, ipr-extern: restrict COMPATIBLE_MACHINE like on libreflexxestype2
* fixes:
ERROR: Nothing PROVIDES 'libreflexxestype2' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/ipr-extern/ros-reflexxes_0.8.8-1.bb DEPENDS on or otherwise requires it)
libreflexxestype2 was skipped: incompatible with machine raspberrypi4 (not in COMPATIBLE_MACHINE)
ERROR: Nothing RPROVIDES 'ros-reflexxes' (but webos-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/ipr-extern/ipr-extern_0.8.8-1.bb, webos-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/ipr-extern/ros-reflexxes_0.8.8-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros-reflexxes'
NOTE: Runtime target 'ros-reflexxes' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-reflexxes']
NOTE: Runtime target 'ipr-extern' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ipr-extern', 'ros-reflexxes']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>