meta-ros-common: speech-tools, festival: Upgrade to latest version and move to meta-ros1
* it's used only by festival which in turn is used only by
  meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb:
  which doesn't exist in either ROS2 distributions, so move
  it all to meta-ros1

* upgrade speech-tools to slightly newer snapshot (still 6+ years old)
  to resolve build issue without -fpermissive:
  | siod.cc: In function 'char** siod_variable_generator(char*, int)':
  | siod.cc:474:18: error: invalid conversion from 'char' to 'char*' [-fpermissive]
  |      matches[i] = '\0';
  |                   ^~~~

  set downloadfilename to make sure that new tarball is being
  fetched instead of reusing the old one from downloads (the
  filename is the same, just the directory from where it's
  fetched is changing).

  Also include the snapshot date in PV to make it visible to
  package manager and users.

* also pass LDFLAGS to resolve following QA issues:

WARNING: speech-tools-2.3.20131016-r0 do_package_qa: QA Issue:
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/scfg_test, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ch_track, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ch_wave, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/wfst_build, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/scfg_make, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ch_utt, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/design_filter, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/tilt_analysis, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/wagon, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ch_lab, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ngram_test, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/wfst_train, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/na_play, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/sigfilter, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/spectgen, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/siod, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/wagon_test, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/pitchmark, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/bcat, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/scfg_parse, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/tilt_synthesis, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/pda, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/sig2fv, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ols, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ngram_build, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/xml_parser, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/dp, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/scfg_train, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/align, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/viterbi, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/ols_test, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/na_record, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary tmp-glibc/work/aarch64-oe-linux/speech-tools/2.3.20131016-r0/packages-split/speech-tools/usr/bin/wfst_run, didn't pass LDFLAGS? [ldflags]

* use SYSROOT_DIRS_append instead of speechtools_sysroot_preprocess
  to share the data with festival build, but we also need to fix CC
  variable when festival is using that, because otherwise it points
  to already removed (with rm_work) speech-tools RSS

* pass LDFLAGS in festival as well:
WARNING: festival-2.3-r0 do_package_qa: QA Issue:
No GNU_HASH in the ELF binary festival/2.3-r0/packages-split/festival/usr/bin/festival, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary festival/2.3-r0/packages-split/festival/usr/bin/festival_client, didn't pass LDFLAGS?
No GNU_HASH in the ELF binary festival/2.3-r0/packages-split/festival/usr/lib/festival/audsp, didn't pass LDFLAGS? [ldflags]

* and use correct form of "cp" to fix
WARNING: festival-2.3-r0 do_package_qa: QA Issue:
festival: /festival/usr/share/festival/dicts/wsj.wp39.poslexR is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/COPYING.poslex is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/wsj.wp39.tri.ngrambin is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.diff is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/allowables.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict_extensions.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmulex.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmu_lts_rules.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmu2ft is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict_compile.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/COPYING is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/Makefile is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/dicts/cmu/cmudict-0.4.out is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/COPYING is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/group/kallpc16k.group is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/festvox/kal_diphone.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination
festival: /festival/usr/share/festival/voices/english/kal_diphone/festvox/kaldurtreeZ.scm is owned by uid 2001, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
Signed-off-by: Martin Jansa <martin.jansa@lge.com>