{melodic} moveit-core: fix installed-vs-shipped and skip dev-so QA issue
* fixes:
WARNING: moveit-core-1.0.2-1-r0 do_package: QA Issue: moveit-core: Files/directories were installed but not shipped in any package:
  /opt/ros/melodic/lib/libmoveit_collision_detection.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_collision_detection_fcl.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_background_processing.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_exceptions.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_profiler.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_planning_scene.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_distance_field.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_planning_interface.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_kinematics_base.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_robot_model.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_kinematic_constraints.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_transforms.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_constraint_samplers.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_collision_distance_field.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_kinematics_metrics.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_trajectory_processing.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_utils.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_robot_state.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_robot_trajectory.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_test_utils.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_dynamics_solver.so.1.0.2
  /opt/ros/melodic/lib/libmoveit_planning_request_adapter.so.1.0.2
  /opt/ros/melodic/lib/libcollision_detector_fcl_plugin.so.1.0.2
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
moveit-core: 23 installed and not shipped files. [installed-vs-shipped]

ERROR: moveit-core-1.0.2-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_background_processing.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_constraint_samplers.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_trajectory_processing.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_test_utils.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_collision_distance_field.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_kinematics_metrics.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_profiler.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_dynamics_solver.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_exceptions.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_robot_model.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_utils.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_planning_interface.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_kinematics_base.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_distance_field.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_collision_detection_fcl.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_transforms.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_robot_state.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_collision_detection.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_kinematic_constraints.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_planning_scene.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libcollision_detector_fcl_plugin.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_planning_request_adapter.so'
non -dev/-dbg/nativesdk- package contains symlink .so: moveit-core path '/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_robot_trajectory.so' [dev-so]

* there is still an issue with build-deps which is only triggered when
  fcl-catkin is built in the same TMPDIR and confuses shlibs code,
  because both fcl and fcl-catkin provide libfcl.so.0.6:
  WARNING: moveit-core-1.0.2-1-r0 do_package_qa: QA Issue: moveit-core rdepends on fcl-catkin, but it isn't a build dependency, missing fcl-catkin in DEPENDS or PACKAGECONFIG? [build-deps]

  from moveit-core log.do_package:
  DEBUG: moveit-core: Dependency libfcl.so.0.6 requires package fcl-catkin (used by files: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_collision_detection_fcl.so.1.0.2)

$ grep libfcl.so tmp-glibc/pkgdata/qemux86-64/runtime/fcl tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERPROVIDESFLIST_fcl: /usr/lib/libfcl.so.0.6.1
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILES_INFO: {"/usr/lib/libfcl.so.0.6.1": 7453512, "/usr/lib/libfcl.so.0.6": 15, "/usr/share/fcl/package.xml": 505}
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERPROVIDES_/usr/lib/libfcl.so.0.6.1_fcl:  libfcl.so.0.6()(64bit)
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERDEPENDSFLIST_fcl: /usr/lib/libfcl.so.0.6.1
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERDEPENDS_/usr/lib/libfcl.so.0.6.1_fcl:  libgcc_s.so.1(GCC_3.0)(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libstdc++.so.6(GLIBCXX_3.4.10)(64bit) libstdc++.so.6(GLIBCXX_3.4.20)(64bit) libstdc++.so.6(CXXABI_1.3.8)(64bit) libstdc++.so.6(GLIBCXX_3.4.18)(64bit) libstdc++.so.6(GLIBCXX_3.4.9)(64bit) libstdc++.so.6(GLIBCXX_3.4.11)(64bit) libstdc++.so.6(CXXABI_1.3)(64bit) libstdc++.so.6(GLIBCXX_3.4.14)(64bit) libstdc++.so.6(GLIBCXX_3.4.21)(64bit) libstdc++.so.6(GLIBCXX_3.4.15)(64bit) libstdc++.so.6(GLIBCXX_3.4.19)(64bit) libstdc++.so.6(GLIBCXX_3.4)(64bit) libccd.so.2()(64bit) liboctomap.so.1.9()(64bit) liboctomath.so.1.9()(64bit) libstdc++.so.6()(64bit) libm.so.6()(64bit) libgcc_s.so.1()(64bit) libc.so.6()(64bit) rtld(GNU_HASH)

tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILERPROVIDESFLIST_fcl-catkin: /opt/ros/melodic/lib/libfcl.so.0.6
tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILES_INFO: {"/opt/ros/melodic/lib/libfcl.so.0.6": 383966168, "/opt/ros/melodic/share/fcl_catkin/package.xml": 350}
tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILERPROVIDES_/opt/ros/melodic/lib/libfcl.so.0.6_fcl-catkin:  libfcl.so.0.6()(64bit)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>