{melodic} control-box-rst, ifopt, mpc-local-planner-examples, mpc-local-planner, towr-ros, towr: blacklist based on separate coinor-libipopt ROS_WORLD_SKIP_GROUPS element
* fixes:
ERROR: Nothing RPROVIDES 'mpc-local-planner' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mpc-local-planner/mpc-local-planner-examples_0.0.2-1.bb RDEPENDS on or otherwise requires it)
mpc-local-planner was skipped: Recipe is blacklisted: Depends on control-box-rst which depends on unavailable UNRESOLVED-coinor-libipopt-dev
NOTE: Runtime target 'mpc-local-planner' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mpc-local-planner']
ERROR: Nothing RPROVIDES 'mpc-local-planner-examples-dev' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mpc-local-planner/mpc-local-planner-examples_0.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mpc-local-planner-examples-dev'
NOTE: Runtime target 'mpc-local-planner-examples-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mpc-local-planner-examples-dev']
ERROR: Nothing RPROVIDES 'mpc-local-planner-examples' (but /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/mpc-local-planner/mpc-local-planner-examples_0.0.2-1.bb, /jenkins/mjansa/build/ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/recipes-core/packagegroups/packagegroup-ros-world-melodic.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'mpc-local-planner-examples'
NOTE: Runtime target 'mpc-local-planner-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mpc-local-planner-examples']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>