{melodic} ainstein-radar-filters, dynamixel-workbench-single-manager, franka-hw, industrial-robot-status-controller, kvh-geo-fog-3d-driver, pacmod, rail-segmentation, rslidar-driver, sick-scan: ignore return-type issues
* fixes:
  ainstein-radar-filters/2.0.2-1-r0/git/include/ainstein_radar_filters/radar_target_kf.h:126:2: error: no return statement in function returning non-void [-Werror=return-type]
  ainstein-radar-filters/2.0.2-1-r0/git/include/ainstein_radar_filters/radar_target_kf.h:58:2: error: no return statement in function returning non-void [-Werror=return-type]
  dynamixel-workbench-single-manager/2.0.0-r0/git/src/single_dynamixel_controller.cpp:115:46: error: control reaches end of non-void function [-Werror=return-type]
  dynamixel-workbench-single-manager/2.0.0-r0/git/src/single_dynamixel_controller.cpp:258:1: error: control reaches end of non-void function [-Werror=return-type]
  dynamixel-workbench-single-manager/2.0.0-r0/git/src/single_dynamixel_controller.cpp:38:1: error: no return statement in function returning non-void [-Werror=return-type]
  franka-hw/0.6.0-1-r0/git/src/franka_hw.cpp:25:1: error: no return statement in function returning non-void [-Werror=return-type]
  industrial-robot-status-controller/0.1.2-1-r0/git/src/controller.cpp:100:1: error: control reaches end of non-void function [-Werror=return-type]
  industrial-robot-status-controller/0.1.2-1-r0/git/src/controller.cpp:89:1: error: control reaches end of non-void function [-Werror=return-type]
  kvh-geo-fog-3d-driver/1.3.3-1-r0/git/src/kvh_driver/driver_main.cpp:310:3: error: no return statement in function returning non-void [-Werror=return-type]
  pacmod/2.1.0-1-r0/git/src/pacmod_ros_msg_handler.cpp:485:1: error: control reaches end of non-void function [-Werror=return-type]
  pacmod/2.1.0-1-r0/git/src/pacmod_ros_msg_handler.cpp:490:24: error: control reaches end of non-void function [-Werror=return-type]
  rail-segmentation/0.1.15-1-r0/git/src/Segmenter.cpp:465:94: error: control reaches end of non-void function [-Werror=return-type]
  rslidar-driver/1.0.2-r0/git/src/input.cc:330:1: error: control reaches end of non-void function [-Werror=return-type]
  sick-scan/1.4.2-1-r0/git/driver/src/dataDumper.cpp:97:1: error: no return statement in function returning non-void [-Werror=return-type]
  sick-scan/1.4.2-1-r0/git/driver/src/sick_scan_common_tcp.cpp:601:3: error: no return statement in function returning non-void [-Werror=return-type]

* intentionally not unblacklisting sick-scan yet, because there are 2
  other issues as well:
  sick-scan/1.4.2-1-r0/git/driver/src/sick_scan_common.cpp:1073:14: error: no match for 'operator==' (operand types are 'boost::system::error_code' and 'int')
  sick-scan/1.4.2-1-r0/git/driver/src/sick_scan_common.cpp:1093:14: error: no match for 'operator!=' (operand types are 'boost::system::error_code' and 'int')

Signed-off-by: Martin Jansa <martin.jansa@lge.com>