{melodic} fcl-catkin: use bitbake fetcher to fetch fcl and fix build with -isystem
* fixes:
DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build --target all -- -j 80
[1/9] cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-build && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/tmp && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-mkdir
[2/9] cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -P ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/download-fcl_src.cmake && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -P ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/verify-fcl_src.cmake && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -P ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/extract-fcl_src.cmake && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-download
-- Downloading...
   dst='ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/v0.6.0.zip'
   timeout='none'
-- Using src='https://github.com/flexible-collision-library/fcl/archive/v0.6.0.zip'
-- [download 100% complete]
-- verifying file...
       file='ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/v0.6.0.zip'
-- Downloading... done
-- extracting...
     src='ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/v0.6.0.zip'
     dst='ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[3/9] cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E echo_append && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-update
[4/9] cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E echo_append && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-patch
[5/9] cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-build && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/install -DFCL_BUILD_TESTS:BOOL=OFF -DFCL_USE_HOST_NATIVE_ARCH:BOOL=OFF -DFCL_USE_X64_SSE:BOOL=OFF -DCMAKE_INSTALL_LIBDIR=lib -GNinja ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-configure
FAILED: fcl_src-prefix/src/fcl_src-stamp/fcl_src-configure
cd ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-build && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/install -DFCL_BUILD_TESTS:BOOL=OFF -DFCL_USE_HOST_NATIVE_ARCH:BOOL=OFF -DFCL_USE_X64_SSE:BOOL=OFF -DCMAKE_INSTALL_LIBDIR=lib -GNinja ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src && ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-stamp/fcl_src-configure
Re-run cmake no build system arguments
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set RPATH explicitly to 'ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/install/lib'
-- Checking for module 'ccd'
--   Found ccd, version 1.5
-- Checking for module 'libccd'
--   No package 'libccd' found
CMake Error at CMakeLists.txt:198 (message):
  CCD is required by FCL

-- Configuring incomplete, errors occurred!
See also "ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/build/fcl_src-prefix/src/fcl_src-build/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/fcl-catkin/0.6.0-1-r0/temp/log.do_compile.6183)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>