{melodic} swri-transform-util: fix build with boost-1.69.0
* fixes:
FAILED: CMakeFiles/swri_transform_util.dir/src/utm_util.cpp.o
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"swri_transform_util\" -Dswri_transform_util_EXPORTS -Iros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/include -Iros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/opt/ros/melodic/include -Iros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -Iros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/usr/include/opencv -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0=/usr/src/debug/swri-transform-util/2.11.0-1-r0                      -fdebug-prefix-map=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0=/usr/src/debug/swri-transform-util/2.11.0-1-r0                      -fdebug-prefix-map=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot -fPIC -MD -MT CMakeFiles/swri_transform_util.dir/src/utm_util.cpp.o -MF CMakeFiles/swri_transform_util.dir/src/utm_util.cpp.o.d -o CMakeFiles/swri_transform_util.dir/src/utm_util.cpp.o -c ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/src/utm_util.cpp
In file included from ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/include/swri_transform_util/utm_util.h:35,
                 from ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/src/utm_util.cpp:30:
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/usr/include/boost/serialization/singleton.hpp: In instantiation of 'boost::serialization::detail::singleton_wrapper<T>::singleton_wrapper() [with T = swri_transform_util::UtmUtil::UtmData]':
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/usr/include/boost/serialization/singleton.hpp:171:47:   required from 'static T& boost::serialization::singleton<T>::get_instance() [with T = swri_transform_util::UtmUtil::UtmData]'
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/usr/include/boost/serialization/singleton.hpp:196:28:   required from 'static const T& boost::serialization::singleton<T>::get_const_instance() [with T = swri_transform_util::UtmUtil::UtmData]'
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/src/utm_util.cpp:182:33:   required from here
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/recipe-sysroot/usr/include/boost/serialization/singleton.hpp:147:24: error: 'swri_transform_util::UtmUtil::UtmData::UtmData()' is private within this context
     singleton_wrapper(){
                        ^
ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/swri-transform-util/2.11.0-1-r0/git/src/utm_util.cpp:84:3: note: declared private here
   UtmUtil::UtmData::UtmData()
   ^~~~~~~
ninja: build stopped: subcommand failed.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>