{melodic} ros-distro.inc: add mapping for protobuf and readline
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-protobuf' (but generated-recipes/rc-dynamics-api/rc-dynamics-api_0.10.0-1.bb, generated-recipes/rc-visard/rc-visard-driver_2.7.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-protobuf' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-protobuf']
NOTE: Runtime target 'rc-visard-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-visard-driver', 'rc-dynamics-api', 'UNRESOLVED-protobuf']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'rc-visard-driver', 'rc-dynamics-api', 'UNRESOLVED-protobuf']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'rc-visard-driver', 'rc-dynamics-api', 'UNRESOLVED-protobuf']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'rc-visard-driver', 'rc-dynamics-api', 'UNRESOLVED-protobuf']
NOTE: Runtime target 'rc-dynamics-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rc-dynamics-api', 'UNRESOLVED-protobuf']

ERROR: Nothing RPROVIDES 'UNRESOLVED-libreadline' (but generated-recipes/yp-spur/ypspur_1.17.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libreadline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libreadline']
NOTE: Runtime target 'ypspur-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ypspur-ros', 'ypspur', 'UNRESOLVED-libreadline']
NOTE: Runtime target 'ypspur' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ypspur', 'UNRESOLVED-libreadline']
NOTE: Runtime target 'ypspur-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ypspur-dev', 'UNRESOLVED-libreadline']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>