ros-distro.conf: don't include ROS_DISTRO in -ROS_DISTRO_METADATA_VERSION_MINOR if it isn't defined
* without ROS_DISTRO in bblayers.conf it causes ugly exception while
  parsing meta-ros:
  https://jenkins-scm.lgsvl.net/job/jansa/job/webosose-jansa-thud-engineering-qemux86/72/console

Parsing recipes...WARNING: /jenkins/home/anaconda/build-webos-ose-thud/build/oe-core/meta/recipes-devtools/python/python3_3.5.6.bb: Exception during build_dependencies for do_compile
WARNING: /jenkins/home/anaconda/build-webos-ose-thud/build/oe-core/meta/recipes-devtools/python/python3_3.5.6.bb: Error during finalise of virtual:nativesdk:/jenkins/home/anaconda/build-webos-ose-thud/build/oe-core/meta/recipes-devtools/python/python3_3.5.6.bb
ERROR: ExpansionError during parsing /jenkins/home/anaconda/build-webos-ose-thud/build/oe-core/meta/recipes-devtools/python/python3_3.5.6.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable do_compile, expression was     set_icecc_env
	# regenerate platform specific files, because they depend on system headers
	cd /jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/Python-3.5.6/Lib/plat-linux*
	include=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include /jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot-native/usr/bin/python3-native/python3 \
		/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/Python-3.5.6/Tools/scripts/h2py.py -i '(u_long)' \
		/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include/dlfcn.h \
		/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include/linux/cdrom.h \
		/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include/netinet/in.h \
		/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include/sys/types.h
	sed -e 's,/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot,,g' -i *.py
	cd -

	# remove any bogus LD_LIBRARY_PATH
	sed -i -e s,RUNSHARED=.*,RUNSHARED=, Makefile

	if [ ! -f Makefile.orig ]; then
		install -m 0644 Makefile Makefile.orig
	fi
	sed -i -e 's,^CONFIGURE_LDFLAGS=.*,CONFIGURE_LDFLAGS=-L. -L/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/lib,g' \
		-e 's,libdir=/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/lib,libdir=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/lib,g' \
		-e 's,libexecdir=/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/libexec,libexecdir=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/libexec,g' \
		-e 's,^LIBDIR=.*,LIBDIR=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/lib,g' \
		-e 's,includedir=/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include,includedir=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include,g' \
		-e 's,^INCLUDEDIR=.*,INCLUDE=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include,g' \
		-e 's,^CONFINCLUDEDIR=.*,CONFINCLUDE=/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr/include,g' \
		Makefile
	# save copy of it now, because if we do it in do_install and
	# then call do_install twice we get Makefile.orig == Makefile.sysroot
	install -m 0644 Makefile Makefile.sysroot

	if ${@bb.utils.contains('PACKAGECONFIG', 'pgo', 'true', 'false', d)}; then
		run_make profile-opt
		qemu_binary="${@qemu_wrapper_cmdline(d, '/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot', ['/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/build', '/jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/recipe-sysroot/${@bb.utils.contains('DISTRO_FEATURES', 'usrmerge', '/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux/usr', '/opt/webos-sdk-x86_64/1.0.g+2.${ROS_DISTRO}.20191214.3/sysroots/x86_64-webossdk-linux', d)}/lib'])}"
		cat >pgo-wrapper <<EOF
cd /jenkins/home/anaconda/build-webos-ose-thud/build/BUILD/work/x86_64-nativesdk-webossdk-linux/nativesdk-python3/3.5.6-r1.0/build
$qemu_binary "\$@"
EOF
		chmod +x pgo-wrapper
		bbnote Gathering profiling data
		./pgo-wrapper ./python -m test.regrtest --pgo test_grammar test_opcodes test_dict test_builtin test_exceptions test_types test_support || true
		bbnote Profiling data gathered, rebuilding
		run_make clean_and_use_profile
	else
		run_make libpython3.so
		run_make
	fi
 which triggered exception SyntaxError: invalid syntax (do_compile, line 1)

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>