{eloquent} ros-distro.inc: add mapping for libusb-dev, libftdi-dev, ftdi-eeprom
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libusb-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/kobuki-ftdi/kobuki-ftdi_1.0.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'kobuki-ftdi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kobuki-ftdi', 'UNRESOLVED-libusb-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-ftdi-eeprom' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/kobuki-ftdi/kobuki-ftdi_1.0.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libftdi-dev

Signed-off-by: Martin Jansa <martin.jansa@lge.com>