meta-ros-common: move bullet and python-matplotlib to meta-ros1
* they depend on python-numpy which I've imported only to meta-ros1 in:
  commit 630d755319c2bb5d33e2f5910877e153eaebc47d
  Author: Martin Jansa <martin.jansa@lge.com>
  Date:   Wed Dec 11 08:20:24 2019 -0800

    Import python-{nose,numpy} removed from oe-core

    * python-nose was removed in:
      http://git.openembedded.org/openembedded-core/commit/?h=zeus&id=9f07b2836405d86e869780f8f1ae00843eadc409
      python-numpy in:
      http://git.openembedded.org/openembedded-core/commit/?h=zeus&id=4e9659f24e2f699effadcbe378b6a746d77ccdbd
      from oe-core/zeus, but catkin and rospy from melodic still depend on
      them, in theory they should be already compatible with python3 as well
      but until we switch the default to python3 we need to import these
      2 recipes

    * for more details see:
      http://lists.openembedded.org/pipermail/openembedded-devel/2019-December/203618.html

* fixes:
ERROR: Nothing PROVIDES 'python-numpy' (but meta-ros/meta-ros-common/recipes-devtools/python/python-matplotlib_2.1.1.bb, meta-ros/meta-ros-common/recipes-extended/bullet/bullet_2.87.bb DEPENDS on or otherwise requires it). Close matches:
  python3-numpy
  python-snimpy
  python-empy
ERROR: Nothing RPROVIDES 'python-numpy' (but meta-ros/meta-ros-common/recipes-devtools/python/python-matplotlib_2.1.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-numpy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-numpy']
ERROR: Nothing RPROVIDES 'python-matplotlib-dev' (but meta-ros/meta-ros-common/recipes-devtools/python/python-matplotlib_2.1.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python-matplotlib-dev'
NOTE: Runtime target 'python-matplotlib-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-matplotlib-dev']
ERROR: Nothing RPROVIDES 'python-matplotlib' (but meta-ros/meta-ros-common/recipes-devtools/python/python-matplotlib_2.1.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python-matplotlib'
NOTE: Runtime target 'python-matplotlib' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-matplotlib']
ERROR: Nothing RPROVIDES 'bullet' (but meta-ros/meta-ros-common/recipes-extended/bullet/bullet_2.87.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'bullet'
NOTE: Runtime target 'bullet' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bullet']
ERROR: Nothing RPROVIDES 'bullet-dev' (but meta-ros/meta-ros-common/recipes-extended/bullet/bullet_2.87.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'bullet-dev'
NOTE: Runtime target 'bullet-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bullet-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>