{melodic} opencv-3.4.5: remove tiny-dnn and fix QA issue in webOS OSE builds
* remove tiny-dnn like newer openCV-4 did in meta-oe commit:
  commit e701e2d5c96efbb3d9b9adb800e8a9cdb61a3f84
  Author: Chin Huat Ang <chin.huat.ang@intel.com>
  Date:   Fri Jun 28 05:46:21 2019 +0800

    opencv: 3.4.5 -> 4.1.0

    Update both opencv and opencv_contrib to 4.1.0 and refresh all patches.

    Remove tiny-dnn from SRC_URI as it is not picked up by opencv cmake
    build system. This also fixes a QA warning about using unstable github
    archive.

  ...

* fixes:
  ERROR: QA Issue: git://github.com/opencv/opencv.git;name=opencv     git://github.com/opencv/opencv_contrib.git;destsuffix=contrib;name=contrib     git://github.com/opencv/opencv_3rdparty.git;branch=ippicv/master_20180723;destsuffix=ipp;name=ipp     git://github.com/opencv/opencv_3rdparty.git;branch=contrib_xfeatures2d_boostdesc_20161012;destsuffix=boostdesc;name=boostdesc     git://github.com/opencv/opencv_3rdparty.git;branch=contrib_xfeatures2d_vgg_20160317;destsuffix=vgg;name=vgg     https://github.com/tiny-dnn/tiny-dnn/archive/v1.0.0a3.tar.gz;destsuffix=git/3rdparty/tinydnn/tiny-dnn-1.0.0a3;name=tinydnn;unpack=false     file://0001-3rdparty-ippicv-Use-pre-downloaded-ipp.patch     file://uselocalxfeatures.patch;patchdir=../contrib/     file://0002-Make-opencv-ts-create-share-library-intead-of-static.patch     file://0003-To-fix-errors-as-following.patch     file://fixpkgconfig.patch     file://0001-Temporarliy-work-around-deprecated-ffmpeg-RAW-functi.patch     file://0001-Dont-use-isystem.patch : SRC_URI uses unstable GitHub archives [src-uri-bad]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>