{melodic} ros-distro.inc: add mapping for liburdfdom-tools
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-liburdfdom-tools' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/moveit/moveit-kinematics_1.0.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-liburdfdom-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-liburdfdom-tools']
NOTE: Runtime target 'moveit-kinematics' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-kinematics', 'UNRESOLVED-liburdfdom-tools']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'moveit-kinematics', 'UNRESOLVED-liburdfdom-tools']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'moveit-kinematics', 'UNRESOLVED-liburdfdom-tools']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'moveit-kinematics', 'UNRESOLVED-liburdfdom-tools']
NOTE: Runtime target 'moveit-kinematics-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['moveit-kinematics-dev', 'UNRESOLVED-liburdfdom-tools']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>