{melodic} geometric-shapes: add missing resource_retriever to CATKIN_DEPENDS
* fixes moveit-ros-perception issue:
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: warning: libresource_retriever.so, needed by ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/lib/libgeometric_shapes.so, not found (try using -rpath or -rpath-link)
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/lib/libgeometric_shapes.so: undefined reference to `resource_retriever::Retriever::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/lib/libgeometric_shapes.so: undefined reference to `resource_retriever::Retriever::~Retriever()'
ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.2.0/ld: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-ros-planning/1.0.2-1-r0/recipe-sysroot/opt/ros/melodic/lib/libgeometric_shapes.so: undefined reference to `resource_retriever::Retriever::Retriever()'
collect2: error: ld returned 1 exit status

Signed-off-by: Martin Jansa <martin.jansa@lge.com>