{melodic} pilz-trajectory-generation: add dependency on pilz-industrial-motion-testutils and blacklist
* add pyassimp to pilz-trajectory-generation ROS_WORLD_SKIP_GROUPS
* drop pilz-trajectory-generation and pilz-industrial-motion-testutils
  from packagegroup-ros-world-melodic based on pyassimp in
  ROS_WORLD_SKIP_GROUPS
* drop pilz-industrial-motion-testutils from
  packagegroup-ros-world-melodic based on opengl ROS_WORLD_SKIP_GROUPS
* adjust PNBLACKLIST texts to use 'pyassimp: ' prefix, so it's easier
  to find and cleanup later when pyassimp recipe is available

* fixes:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/devel
-- Using CMAKE_PREFIX_PATH: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic;/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/usr
-- This workspace overlays: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic
-- Found PythonInterp: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/python-native/python2 (found suitable version "2.7.16", minimum required is "2")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/bin/python-native/python2
-- Using default Python package layout
-- Found PY_em: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using empy: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;gennodejs;genpy
-- Could NOT find pilz_industrial_motion_testutils (missing: pilz_industrial_motion_testutils_DIR)
-- Could not find the required component 'pilz_industrial_motion_testutils'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/recipe-sysroot/opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "pilz_industrial_motion_testutils" with any of the following names:

    pilz_industrial_motion_testutilsConfig.cmake
    pilz_industrial_motion_testutils-config.cmake

  Add the installation prefix of "pilz_industrial_motion_testutils" to
  CMAKE_PREFIX_PATH or set "pilz_industrial_motion_testutils_DIR" to a
  directory containing one of the above files.  If
  "pilz_industrial_motion_testutils" provides a separate development package
  or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/pilz-trajectory-generation/0.4.10-1-r0/temp/log.do_configure.42975)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>