rclcpp: add missing dependency
* fixes:
RROR: rclcpp-0.8.3-1-r0 do_compile: Function failed: do_compile (log file is located at /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/temp/log.do_compile.25061)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/temp/log.do_compile.25061
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: VERBOSE=1 cmake --build /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/build --target all -- -j 32
| [1/56] cd /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/build && /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory include/rclcpp && /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 -c "import em;em.invoke(['-o', 'include/rclcpp/logging.hpp', '/jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/git/resource/logging.hpp.em'])"
| FAILED: include/rclcpp/logging.hpp
| cd /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/build && /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/recipe-sysroot-native/usr/bin/cmake -E make_directory include/rclcpp && /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 -c "import em;em.invoke(['-o', 'include/rclcpp/logging.hpp', '/jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/git/resource/logging.hpp.em'])"
| Traceback (most recent call last):
|   File "<string>", line 1, in <module>
| ModuleNotFoundError: No module named 'em'
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rclcpp/0.8.3-1-r0/temp/log.do_compile.25061)
NOTE: recipe rclcpp-0.8.3-1-r0: task do_compile: Failed
ERROR: Task (/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rclcpp/rclcpp_0.8.3-1.bb:do_compile) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>