{foxy} ros-workspace: import bbappends from eloquent and set ROS_BUILD_TYPE
* without ROS_BUILD_TYPE changed from cmake to ament_cmake
  we end without python3native inherit which results in using
  python3 from host which doesn't have various ROS specific
  python modules available and ros-workspace fails like this:

-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
Traceback (most recent call last):
  File "/jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/ros-workspace/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
    from ament_package.templates import get_environment_hook_template_path
ModuleNotFoundError: No module named 'ament_package'
CMake Error at /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/ros-workspace/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_core/cmake/ament_cmake_package_templates-extras.cmake:41 (message):
  execute_process(/usr/bin/python3
  /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/ros-workspace/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py
  /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/ros-workspace/1.0.0-1-r0/build/ament_cmake_package_templates/templates.cmake)
  returned error code 1
Call Stack (most recent call first):
  /jenkins/mjansa/build/ros/ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/ros-workspace/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)
  CMakeLists.txt:4 (find_package)

  we should try to fix some of these components by inheritting python3native
  instead of changing ROS_BUILD_TYPE, I've already tested on
  ros-workspace that python3native inherit is enough to build and
  it ends only with unpackaged files in /usr/share/ament_index
  but for now change ROS_BUILD_TYPE like other ROS2 distros does and
  revisit this independently later

Signed-off-by: Martin Jansa <martin.jansa@lge.com>