{melodic} ros-distro.inc: add mapping for libqwt-qt5-dev
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libqwt-qt5-dev' (but generated-recipes/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rqt-multiplot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-multiplot', 'UNRESOLVED-libqwt-qt5-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>