ros2-python-recipe-blacklist.inc: blacklist python-pyassimp
* fixes:
ERROR: Nothing PROVIDES 'python' (but /jenkins/home/workspace/jansa/ros2-eloquent-thud/ros2-eloquent-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-pyassimp_4.1.4.bb DEPENDS on or otherwise requires it)
python was skipped: Recipe is blacklisted: ROS 2 is Python 3 only
ERROR: Nothing RPROVIDES 'python-pyassimp-dev' (but /jenkins/home/workspace/jansa/ros2-eloquent-thud/ros2-eloquent-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-pyassimp_4.1.4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python-pyassimp-dev'
NOTE: Runtime target 'python-pyassimp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-pyassimp-dev']
ERROR: Nothing RPROVIDES 'python-core' (but /jenkins/home/workspace/jansa/ros2-eloquent-thud/ros2-eloquent-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-pyassimp_4.1.4.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-core']
ERROR: Nothing RPROVIDES 'python-pyassimp' (but /jenkins/home/workspace/jansa/ros2-eloquent-thud/ros2-eloquent-thud/meta-ros/meta-ros-common/recipes-devtools/python/python-pyassimp_4.1.4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python-pyassimp'
NOTE: Runtime target 'python-pyassimp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-pyassimp']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>