{eloquent} nav2-costmap-2d: fix dependencies
* fixes:
DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.8.2 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/ament_cmake/cmake)
-- Found PythonInterp: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.6", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found geometry_msgs: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/geometry_msgs/cmake)
CMake Warning at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/rosidl_generator_cppConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/std_msgs/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/std_msgs/cmake/std_msgsConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/geometry_msgs/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/geometry_msgs/cmake/geometry_msgsConfig.cmake:38 (include)
  CMakeLists.txt:5 (find_package)

-- Found laser_geometry: 2.1.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/laser_geometry/cmake)
-- append /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/include/eigen3 to ()
-- laser_geometry_INCLUDE_DIRS=/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/include/eigen3
CMake Error at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/laser_geometry/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
  By not providing "Findeigen3_cmake_module.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "eigen3_cmake_module", but CMake did not find one.

  Could not find a package configuration file provided by
  "eigen3_cmake_module" with any of the following names:

    eigen3_cmake_moduleConfig.cmake
    eigen3_cmake_module-config.cmake

  Add the installation prefix of "eigen3_cmake_module" to CMAKE_PREFIX_PATH
  or set "eigen3_cmake_module_DIR" to a directory containing one of the above
  files.  If "eigen3_cmake_module" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/recipe-sysroot/usr/share/laser_geometry/cmake/laser_geometryConfig.cmake:38 (include)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/nav2-costmap-2d/0.3.2-1-r0/temp/log.do_configure.10346)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>