{melodic} kobuki-ftdi: fix dependencies
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-ftdi-eeprom' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/kobuki-core/kobuki-ftdi_0.7.8.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'kobuki-ftdi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kobuki-ftdi', 'UNRESOLVED-ftdi-eeprom']
NOTE: Runtime target 'kobuki-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kobuki-core', 'kobuki-ftdi', 'UNRESOLVED-ftdi-eeprom']

and

DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake_ros: 0.8.0 (/jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
-- Found PythonInterp: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.6", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found ecl_build: 1.0.2 (/jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot/usr/share/ecl_build/cmake)
-- Found ecl_command_line: 1.0.6 (/jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot/usr/share/ecl_command_line/cmake)
-- Found PkgConfig: /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/bin/pkg-config (found version "0.29.2")
-- Checking for one of the modules 'libusb'
CMake Error at /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/share/cmake-3.14/Modules/FindPkgConfig.cmake:701 (message):
  None of the required 'libusb' found
Call Stack (most recent call first):
  CMakeLists.txt:18 (pkg_search_module)

-- Checking for one of the modules 'libftdi'
CMake Error at /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/recipe-sysroot-native/usr/share/cmake-3.14/Modules/FindPkgConfig.cmake:701 (message):
  None of the required 'libftdi' found
Call Stack (most recent call first):
  CMakeLists.txt:19 (pkg_search_module)

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros1-melodic-warrior/tmp-glibc/work/core2-64-oe-linux/kobuki-ftdi/1.0.0-1-r0/temp/log.do_configure.43919)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>