{melodic} ubiquity-motor: fix typo in shebang
* fixes:
  ERROR: ubiquity-motor-0.10.0-1-r0 do_package_qa: QA Issue:
  /usr/opt/ros/melodic/lib/ubiquity_motor/test_motor_board.py contained in
  package ubiquity-motor requires /usr/bin/pythmn, but no providers found
  in RDEPENDS_ubiquity-motor? [file-rdeps]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>