{melodic} librealsense2: remove runtime dependency on virtual/kernel
* fixes:
ERROR: Nothing RPROVIDES 'virtual/kernel' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/librealsense2/librealsense2_2.31.0-3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'virtual/kernel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['virtual/kernel']
NOTE: Runtime target 'librealsense2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librealsense2', 'virtual/kernel']
NOTE: Runtime target 'librealsense2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['librealsense2-dev', 'virtual/kernel']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>