{foxy} control-box-rst: blacklist because it depends on unavailable coinor-libipopt
* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'UNRESOLVED-coinor-libipopt-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/control-box-rst/control-box-rst_0.0.6-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'UNRESOLVED-coinor-libipopt-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/control-box-rst/control-box-rst_0.0.6-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-coinor-libipopt-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-coinor-libipopt-dev']
ERROR: Nothing RPROVIDES 'control-box-rst' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/control-box-rst/control-box-rst_0.0.6-1.bb, ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'control-box-rst'
NOTE: Runtime target 'control-box-rst' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['control-box-rst']
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'control-box-rst']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'control-box-rst']
ERROR: Nothing RPROVIDES 'control-box-rst-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/control-box-rst/control-box-rst_0.0.6-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'control-box-rst-dev'
NOTE: Runtime target 'control-box-rst-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['control-box-rst-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>