{foxy} Add connext to ROS_WORLD_SKIP_GROUPS
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-rti-connext-dds-5.3.1' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rmw-connext/rmw-connext-shared-cpp_0.9.0-1.bb, ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rmw-connext/rmw-connext-cpp_0.9.0-1.bb, ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/connext-cmake-module_0.9.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rmw-connext-shared-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmw-connext-shared-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'rmw-connext-shared-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'rmw-connext-shared-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'rmw-connext-shared-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1']
NOTE: Runtime target 'rmw-connext-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmw-connext-cpp', 'rmw-connext-shared-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1']
NOTE: Runtime target 'connext-cmake-module' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['connext-cmake-module', 'UNRESOLVED-rti-connext-dds-5.3.1']
ERROR: Nothing PROVIDES 'rmw-connext-shared-cpp' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rmw-connext/rmw-connext-cpp_0.9.0-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'rmw-connext-shared-cpp'
ERROR: Nothing PROVIDES 'UNRESOLVED-rti-connext-dds-5.3.1-native' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-cpp_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/connext-cmake-module_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-cpp_0.9.0-1.bb DEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['shape-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['common-interfaces', 'shape-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['composition-interfaces', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rcl-interfaces', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['statistics-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['stereo-msgs', 'sensor-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['sensor-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['unique-identifier-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['test-msgs', 'action-msgs', 'unique-identifier-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['action-msgs', 'unique-identifier-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['visualization-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['lifecycle-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['diagnostic-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['nav-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rmw-dds-common', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['trajectory-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['actionlib-msgs', 'std-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['geometry-msgs', 'std-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['std-msgs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rosgraph-msgs', 'builtin-interfaces', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['builtin-interfaces', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['std-srvs', 'rosidl-default-runtime', 'rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rosidl-typesupport-cpp', 'rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
NOTE: Runtime target 'rosidl-typesupport-connext-cpp' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosidl-typesupport-connext-cpp', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rosidl-typesupport-c', 'rosidl-typesupport-connext-c', 'connext-cmake-module-native', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
NOTE: Runtime target 'rosidl-typesupport-connext-c' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosidl-typesupport-connext-c', 'connext-cmake-module-native', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
Missing or unbuildable dependency chain was: ['rosidl-default-generators', 'rosidl-typesupport-cpp-native', 'rosidl-typesupport-connext-cpp-native', 'connext-cmake-module-native', 'UNRESOLVED-rti-connext-dds-5.3.1-native']
ERROR: Nothing RPROVIDES 'rmw-connext-shared-cpp-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rmw-connext/rmw-connext-shared-cpp_0.9.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmw-connext-shared-cpp-dev'
NOTE: Runtime target 'rmw-connext-shared-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmw-connext-shared-cpp-dev']
ERROR: Nothing RPROVIDES 'rmw-connext-cpp-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rmw-connext/rmw-connext-cpp_0.9.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rmw-connext-cpp-dev'
NOTE: Runtime target 'rmw-connext-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rmw-connext-cpp-dev']
ERROR: Nothing RPROVIDES 'rosidl-typesupport-connext-c-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-c_0.9.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rosidl-typesupport-connext-c-dev'
NOTE: Runtime target 'rosidl-typesupport-connext-c-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosidl-typesupport-connext-c-dev']
ERROR: Nothing RPROVIDES 'rosidl-typesupport-connext-cpp-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-cpp_0.9.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rosidl-typesupport-connext-cpp-dev'
NOTE: Runtime target 'rosidl-typesupport-connext-cpp-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosidl-typesupport-connext-cpp-dev']
ERROR: Nothing RPROVIDES 'connext-cmake-module-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/connext-cmake-module_0.9.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'connext-cmake-module-dev'
NOTE: Runtime target 'connext-cmake-module-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['connext-cmake-module-dev']
ERROR: Nothing RPROVIDES 'rosidl-parser-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-python/rosidl-generator-py_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl/rosidl-cmake_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl/rosidl-generator-c_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl/rosidl-typesupport-introspection-cpp_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl/rosidl-generator-cpp_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl/rosidl-typesupport-introspection-c_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-cpp_0.9.0-1.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'rmw-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-python/rosidl-generator-py_0.9.0-1.bb, virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport-connext/rosidl-typesupport-connext-cpp_0.9.0-1.bb DEPENDS on or otherwise requires it). Close matches:
ERROR: Nothing PROVIDES 'rosidl-typesupport-connext-c-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/rosidl-typesupport/rosidl-typesupport-c_0.9.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  rosidl-typesupport-connext-c
  rosidl-typesupport-connext-cpp-native

Signed-off-by: Martin Jansa <martin.jansa@lge.com>