{eloquent} ros-distro-recipe-blacklist.inc: add few more entries detected with bitbake world
* these were shown only in webOS OSE build which doesn't have x11
  in DISTRO_FEATURES

* fixes:

ERROR: Nothing PROVIDES 'rviz-common' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-rendering' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'rviz-ogre-vendor' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb DEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'rviz-common' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb, meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-common was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-common']
ERROR: Nothing RPROVIDES 'rviz-visual-testing-framework' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-testing-framework'
NOTE: Runtime target 'rviz-visual-testing-framework' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-testing-framework']
ERROR: Nothing RPROVIDES 'rviz-visual-testing-framework-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-visual-testing-framework_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-visual-testing-framework-dev'
NOTE: Runtime target 'rviz-visual-testing-framework-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-visual-testing-framework-dev']
ERROR: Nothing RPROVIDES 'rviz-rendering-tests' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-rendering-tests'
NOTE: Runtime target 'rviz-rendering-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering-tests']
ERROR: Nothing RPROVIDES 'rviz-rendering-tests-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz-rendering-tests-dev'
NOTE: Runtime target 'rviz-rendering-tests-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering-tests-dev']
ERROR: Nothing RPROVIDES 'rviz-rendering' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz-rendering-tests_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-rendering was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-rendering' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-rendering']
ERROR: Nothing RPROVIDES 'rviz-default-plugins' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; x11: depends on rviz-ogre-vendor->(libx11,libxrandr,libxaw) which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-default-plugins']
ERROR: Nothing RPROVIDES 'rviz2-dev' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz2-dev'
NOTE: Runtime target 'rviz2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2-dev']
ERROR: Nothing RPROVIDES 'rviz-ogre-vendor' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
rviz-ogre-vendor was skipped: Recipe is blacklisted: opengl: depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-ogre-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-ogre-vendor']
ERROR: Nothing RPROVIDES 'rviz2' (but meta-ros/meta-ros2-eloquent/generated-recipes/rviz/rviz2_7.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'rviz2'
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>