{melodic} Remove network-autoconfig rdepending on unavailable network-manager
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-network-manager' (but generated-recipes/network-autoconfig/network-autoconfig_0.1.1-2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-network-manager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-network-manager']
NOTE: Runtime target 'network-autoconfig' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['network-autoconfig', 'UNRESOLVED-network-manager']
NOTE: Runtime target 'network-autoconfig-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['network-autoconfig-dev', 'UNRESOLVED-network-manager']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>