{foxy} uncrustify-vendor: remove dependency on uncrustify
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-uncrustify' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/uncrustify-vendor/uncrustify-vendor_1.4.0-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'uncrustify-vendor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uncrustify-vendor', 'UNRESOLVED-uncrustify']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'uncrustify-vendor', 'UNRESOLVED-uncrustify']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'uncrustify-vendor', 'UNRESOLVED-uncrustify']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'uncrustify-vendor', 'UNRESOLVED-uncrustify']
NOTE: Runtime target 'ament-uncrustify' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-uncrustify', 'uncrustify-vendor', 'UNRESOLVED-uncrustify']
ERROR: Nothing RPROVIDES 'uncrustify-vendor-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/uncrustify-vendor/uncrustify-vendor_1.4.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'uncrustify-vendor-dev'
NOTE: Runtime target 'uncrustify-vendor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uncrustify-vendor-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-uncrustify' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/uncrustify-vendor/uncrustify-vendor_1.4.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-uncrustify' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-uncrustify']
ERROR: Nothing RPROVIDES 'ament-uncrustify-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-uncrustify_0.9.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ament-uncrustify-dev'
NOTE: Runtime target 'ament-uncrustify-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-uncrustify-dev']
ERROR: Nothing RPROVIDES 'uncrustify-vendor-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-uncrustify_0.9.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'uncrustify-vendor-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uncrustify-vendor-native']
NOTE: Runtime target 'ament-cmake-uncrustify' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-uncrustify', 'ament-uncrustify-native', 'uncrustify-vendor-native']
NOTE: Runtime target 'ament-cmake-uncrustify-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-uncrustify-dev', 'ament-uncrustify-native', 'uncrustify-vendor-native']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>