{melodic} add new ROS_WORLD_SKIP_GROUPS element osg and blacklist recipes depending on libopenscenegraph
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libopenscenegraph' (but generated-recipes/uwsim-osgworks/uwsim-osgworks_3.0.3-2.bb, generated-recipes/uwsim-osgbullet/uwsim-osgbullet_3.0.1-3.bb, generated-recipes/uwsim-osgocean/uwsim-osgocean_1.0.4-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'uwsim-osgworks' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgworks', 'UNRESOLVED-libopenscenegraph']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'uwsim-osgworks', 'UNRESOLVED-libopenscenegraph']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-osgworks', 'UNRESOLVED-libopenscenegraph']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'uwsim-osgworks', 'UNRESOLVED-libopenscenegraph']
NOTE: Runtime target 'uwsim-osgbullet' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgbullet', 'uwsim-osgworks', 'UNRESOLVED-libopenscenegraph']
NOTE: Runtime target 'uwsim-osgocean' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uwsim-osgocean', 'UNRESOLVED-libopenscenegraph']
ERROR: Nothing PROVIDES 'uwsim-osgworks' (but generated-recipes/uwsim-osgbullet/uwsim-osgbullet_3.0.1-3.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'uwsim-osgworks'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>