{melodic} opencv-apps: Rename the main package to opencv-apps-ros
* to prevent conflict with opencv-apps package from opencv recipe
* fixes:
ERROR: opencv-apps-2.0.1-1-r0 do_packagedata: The recipe opencv-apps is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  ros1-melodic-dunfell/tmp-glibc/pkgdata/raspberrypi4-64/runtime/opencv-apps.packaged
    (matched in manifest-raspberrypi4_64-opencv.packagedata)
  ros1-melodic-dunfell/tmp-glibc/pkgdata/raspberrypi4-64/runtime/opencv-apps
    (matched in manifest-raspberrypi4_64-opencv.packagedata)
Please verify which recipe should provide the above files.

The build has stopped, as continuing in this scenario WILL break things - if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would, however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error, however switching DISTRO_FEATURES on an existing build directory is not supported - you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.
ERROR: opencv-apps-2.0.1-1-r0 do_packagedata: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.
ERROR: Logfile of failure stored in: ros1-melodic-dunfell/tmp-glibc/work/aarch64-oe-linux/opencv-apps/2.0.1-1-r0/temp/log.do_packagedata.63614
NOTE: recipe opencv-apps-2.0.1-1-r0: task do_packagedata: Failed

and

ERROR: opencv-apps-2.0.1-1-r0 do_package_qa: QA Issue: opencv-apps-ros: found library in wrong location: /usr/opt/ros/melodic/lib/libopencv_apps.so [libdir]

Signed-off-by: Martin Jansa <martin.jansa@lge.com>