{melodic} ros-distro.inc: add mapping for python-pydot
* now when it's imported from meta-jupyter, we can unblacklist
  py-trees and resolve:
ERROR: Nothing RPROVIDES 'UNRESOLVED-python-pydot' (but generated-recipes/qt-gui-core/qt-dotgraph_0.3.16-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python-pydot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python-pydot']
NOTE: Runtime target 'qt-gui-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-core', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'qt-gui-core', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'qt-gui-core', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'qt-gui-core', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'qt-gui-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-gui-core-dev', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'rqt-tf-tree' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-tf-tree', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'rqt-dep' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-dep', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'qt-dotgraph' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'rqt-graph' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-graph', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
NOTE: Runtime target 'rqt-graph-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-graph-dev', 'qt-dotgraph', 'UNRESOLVED-python-pydot']
ERROR: Nothing RPROVIDES 'qt-dotgraph-dev' (but generated-recipes/qt-gui-core/qt-dotgraph_0.3.16-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qt-dotgraph-dev'
NOTE: Runtime target 'qt-dotgraph-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qt-dotgraph-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>