{eloquent} packagegroup-ros-world-eloquent: remove dolly, dolly-gazebo, nav2-system-tests without ros-gazebo in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libgazebo9-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-rosdev_3.4.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'gazebo-rosdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'dolly-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo', 'gazebo-ros-pkgs', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'dolly' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly', 'dolly-gazebo', 'gazebo-ros-pkgs', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'dolly-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-dev', 'dolly-gazebo', 'gazebo-ros-pkgs', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'dolly-gazebo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dolly-gazebo-dev', 'gazebo-ros-pkgs', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros-pkgs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs-dev', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
ERROR: Nothing PROVIDES 'gazebo-rosdev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-plugins_3.4.2-1.bb, /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-ros_3.4.2-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'gazebo-rosdev'
ERROR: Nothing PROVIDES 'gazebo-ros' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-plugins_3.4.2-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'gazebo-ros'
ERROR: Nothing RPROVIDES 'gazebo-rosdev-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-rosdev_3.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-rosdev-dev'
NOTE: Runtime target 'gazebo-rosdev-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-rosdev-dev']
ERROR: Nothing RPROVIDES 'gazebo-plugins-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-plugins_3.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-plugins-dev'
NOTE: Runtime target 'gazebo-plugins-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins-dev']
ERROR: Nothing RPROVIDES 'gazebo-ros-dev' (but /jenkins/mjansa/build-ros/ros2-eloquent-warrior/meta-ros/meta-ros2-eloquent/generated-recipes/gazebo-ros-pkgs/gazebo-ros_3.4.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'gazebo-ros-dev'
NOTE: Runtime target 'gazebo-ros-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>