ros-distro-platform-recipe-blacklist.inc: don't blacklist recipes with multiple version
* we would need to blacklist also all users of such recipes
  and we don't need to be so restrictive

* fixes:
ERROR: Nothing RPROVIDES 'php-cli' (but meta-openembedded/meta-oe/recipes-benchmark/phoronix-test-suite/phoronix-test-suite_8.0.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'php-cli' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['php-cli']
ERROR: Nothing RPROVIDES 'phoronix-test-suite' (but meta-openembedded/meta-oe/recipes-benchmark/phoronix-test-suite/phoronix-test-suite_8.0.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'phoronix-test-suite'
NOTE: Runtime target 'phoronix-test-suite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phoronix-test-suite']
ERROR: Nothing RPROVIDES 'phoronix-test-suite-dev' (but meta-openembedded/meta-oe/recipes-benchmark/phoronix-test-suite/phoronix-test-suite_8.0.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'phoronix-test-suite-dev'
NOTE: Runtime target 'phoronix-test-suite-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phoronix-test-suite-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>