{melodic} moveit-core: add dependency on fcl-catkin
* Just to get rid of bogus QA issue, because both fcl and fcl-catkin provide the same libfcl.so.0.6 library, luckily in different paths (so that they don't conflict in RSS):
  fcl-catkin: /opt/ros/melodic/lib/libfcl.so.0.6
  fcl: /usr/lib/libfcl.so.0.6
  which confuses shlibs code and causes:
  ERROR: QA Issue: moveit-core rdepends on fcl-catkin, but it isn't a build dependency, missing fcl-catkin in DEPENDS or PACKAGECONFIG? [build-deps]

* only triggered when fcl-catkin is built in the same TMPDIR

  from moveit-core log.do_package:
  DEBUG: moveit-core: Dependency libfcl.so.0.6 requires package fcl-catkin (used by files: /jenkins/mjansa/build/ros/ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/moveit-core/1.0.2-1-r0/packages-split/moveit-core/opt/ros/melodic/lib/libmoveit_collision_detection_fcl.so.1.0.2)

$ grep libfcl.so tmp-glibc/pkgdata/qemux86-64/runtime/fcl tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERPROVIDESFLIST_fcl: /usr/lib/libfcl.so.0.6.1
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILES_INFO: {"/usr/lib/libfcl.so.0.6.1": 7453512, "/usr/lib/libfcl.so.0.6": 15, "/usr/share/fcl/package.xml": 505}
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERPROVIDES_/usr/lib/libfcl.so.0.6.1_fcl:  libfcl.so.0.6()(64bit)
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERDEPENDSFLIST_fcl: /usr/lib/libfcl.so.0.6.1
tmp-glibc/pkgdata/qemux86-64/runtime/fcl:FILERDEPENDS_/usr/lib/libfcl.so.0.6.1_fcl:  libgcc_s.so.1(GCC_3.0)(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libstdc++.so.6(GLIBCXX_3.4.10)(64bit) libstdc++.so.6(GLIBCXX_3.4.20)(64bit) libstdc++.so.6(CXXABI_1.3.8)(64bit) libstdc++.so.6(GLIBCXX_3.4.18)(64bit) libstdc++.so.6(GLIBCXX_3.4.9)(64bit) libstdc++.so.6(GLIBCXX_3.4.11)(64bit) libstdc++.so.6(CXXABI_1.3)(64bit) libstdc++.so.6(GLIBCXX_3.4.14)(64bit) libstdc++.so.6(GLIBCXX_3.4.21)(64bit) libstdc++.so.6(GLIBCXX_3.4.15)(64bit) libstdc++.so.6(GLIBCXX_3.4.19)(64bit) libstdc++.so.6(GLIBCXX_3.4)(64bit) libccd.so.2()(64bit) liboctomap.so.1.9()(64bit) liboctomath.so.1.9()(64bit) libstdc++.so.6()(64bit) libm.so.6()(64bit) libgcc_s.so.1()(64bit) libc.so.6()(64bit) rtld(GNU_HASH)

tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILERPROVIDESFLIST_fcl-catkin: /opt/ros/melodic/lib/libfcl.so.0.6
tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILES_INFO: {"/opt/ros/melodic/lib/libfcl.so.0.6": 383966168, "/opt/ros/melodic/share/fcl_catkin/package.xml": 350}
tmp-glibc/pkgdata/qemux86-64/runtime/fcl-catkin:FILERPROVIDES_/opt/ros/melodic/lib/libfcl.so.0.6_fcl-catkin:  libfcl.so.0.6()(64bit)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>