{melodic} ethercat-hardware: fix build without catkin testing enabled
* use CATKIN_ENABLE_TESTING conditional as suggested in
  http://docs.ros.org/jade/api/catkin/html/howto/format2/gtest_configuration.html
* otherwise do_configure fails with:
  recipe-sysroot-native/opt/ros/melodic/share/catkin/cmake/test/tests.cmake:18 (message):
  () is not available when tests are not enabled.  The CMake code should only
  use it inside a conditional block which checks that testing is enabled:

  if(CATKIN_ENABLE_TESTING)

    (...)

  endif()
* fixes:

DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-gcc
-- Check for working C compiler: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++
-- Check for working CXX compiler: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/i586-webos-linux/i586-webos-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/devel
-- Using CMAKE_PREFIX_PATH: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot/usr/opt/ros/melodic;webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot/usr
-- This workspace overlays: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot/usr/opt/ros/melodic
-- Found PythonInterp: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/python-native/python2 (found suitable version "2.7.16", minimum required is "2")
-- Using PYTHON_EXECUTABLE: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/bin/python-native/python2
-- Using default Python package layout
-- Found PY_em: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using empy: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;gennodejs;genpy
-- Found EML: webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot/usr/lib/libeml.so
-- ethercat_hardware: 7 messages, 3 services
Install RPATH for ethercat_hardware is /usr/opt/ros/melodic/lib
--
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   regex
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
CMake Error at webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/recipe-sysroot/usr/opt/ros/melodic/share/catkin/cmake/test/tests.cmake:18 (message):
  () is not available when tests are not enabled.  The CMake code should only
  use it inside a conditional block which checks that testing is enabled:

  if(CATKIN_ENABLE_TESTING)

    (...)

  endif()

Call Stack (most recent call first):
  CMakeLists.txt:68 (catkin_add_gtest)

-- Configuring incomplete, errors occurred!
See also "webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at webos-melodic-thud/tmp-glibc/work/qemux86-webos-linux/ethercat-hardware/1.8.19-1-r0/temp/log.do_configure.78834)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>