{eloquent} ros2-ouster: fix dependencies
* fixes:

DEBUG: Executing shell function do_configure
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc
-- Check for working C compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++
-- Check for working CXX compiler: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.8.2 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/ament_cmake/cmake)
-- Found PythonInterp: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.6", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found rclcpp: 0.8.4 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rclcpp/cmake)
CMake Warning at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmake-extras.cmake:30 (find_package):
  By not providing "Findrosidl_adapter.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rosidl_adapter", but CMake did not find one.

  Could not find a package configuration file provided by "rosidl_adapter"
  with any of the following names:

    rosidl_adapterConfig.cmake
    rosidl_adapter-config.cmake

  Add the installation prefix of "rosidl_adapter" to CMAKE_PREFIX_PATH or set
  "rosidl_adapter_DIR" to a directory containing one of the above files.  If
  "rosidl_adapter" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_cmake/cmake/rosidl_cmakeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_generator_cpp/cmake/rosidl_generator_cppConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtime-extras.cmake:12 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rosidl_default_runtime/cmake/rosidl_default_runtimeConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rcl_interfaces/cmake/rcl_interfacesConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rcl/cmake/rclConfig.cmake:38 (include)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rclcpp/cmake/rclcppConfig.cmake:38 (include)
  CMakeLists.txt:5 (find_package)

-- Found rmw_implementation_cmake: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rmw_implementation_cmake/cmake)
-- Using RMW implementation 'rmw_fastrtps_cpp' as default
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found rclcpp_lifecycle: 0.8.4 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rclcpp_lifecycle/cmake)
-- Found rclcpp_components: 0.8.4 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/rclcpp_components/cmake)
-- Found poco_vendor:  (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/poco_vendor/cmake)
-- Found std_msgs: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/std_msgs/cmake)
-- Found std_srvs: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/std_srvs/cmake)
-- Found sensor_msgs: 0.8.1 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/sensor_msgs/cmake)
-- Found tf2_geometry_msgs: 0.12.5 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/tf2_geometry_msgs/cmake)
-- Found pcl_conversions: 2.1.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/pcl_conversions/cmake)
-- Found ouster_msgs: 0.1.0 (/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/share/ouster_msgs/cmake)
-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.7
-- Found eigen: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/include/eigen3
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
-- looking for PCL_COMMON
-- Found PCL_COMMON: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libpcl_common.so
-- Found PCL: /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_system-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_filesystem-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_thread-mt.so;-lpthread;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_date_time-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_iostreams-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_serialization-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_chrono-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_atomic-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_regex-mt.so;optimized;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libpcl_common.so;debug;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libpcl_common.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_system-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_filesystem-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_thread-mt.so;-lpthread;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_date_time-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_iostreams-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_serialization-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_chrono-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_atomic-mt.so;/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/recipe-sysroot/usr/lib/libboost_regex-mt.so
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "Findjsoncpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "jsoncpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "/jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros/ros2-eloquent-warrior/tmp-glibc/work/core2-64-oe-linux/ros2-ouster/0.1.0-1-r0/temp/log.do_configure.56985)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>